---
title: "scores"
output: github_document
---


```{r}
library(tidyverse)
library(neon4cast)
```


```{r}
targets <-
  "https://data.ecoforecast.org/targets/beetles/beetles-targets.csv.gz" %>% 
  read_csv(col_types = "cDdd")

top_sites <- targets %>% as_tibble() %>% filter(time > as.Date("2018-01-01")) %>% 
  select(siteID, time) %>% distinct()  %>% count(siteID, sort=TRUE) %>% pull(siteID) %>% head()
```




```{r}
## Why so many observations have abundance but not richness?
targets %>% filter(time > as.Date("2021-05-01")) %>% as_tibble() %>%
  mutate(has_richness = !is.na(richness), has_abund = !is.na(abundance)) %>% 
  count(has_abund, has_richness)

tidy_targets %>% filter(time > as.Date("2021-05-01"), !is.na(obs)) %>% as_tibble() %>% count(target)
```




```{r}
tidy_targets <- targets %>% pivot_longer(c("abundance", "richness"),
                                        names_to = "target", values_to = "obs")
```


```{r}
files <- fs::dir_ls(glob = "beetles*.csv.gz")

#forecast <- read_csv(files, id = "file")

forecast <- map_dfr(files, read_csv, show_col_types = FALSE, .id = "file")


gsub(pattern,"\\1", file)

pattern<- "(\\w+)\\-(\\d{4}\\-\\d{2}\\-\\d{2})\\-(\\w+)\\.csv\\.gz"
gsub(pattern,"\\1", file)

target_variables <- c("abundance", "richness")

## assumes mean-sd form
tidy_forecast <- forecast %>% 
  mutate(theme = gsub(pattern, "\\1", file),
         issue_date = gsub(pattern, "\\2", file),
         team = gsub(pattern, "\\3", file)) %>%
  pivot_longer(tidyselect::any_of(target_variables), 
               names_to = "target", values_to = "value") %>%
  pivot_wider(values_from=value, names_from = statistic)
```


```{r}
combined <- tidy_forecast %>% left_join(tidy_targets)
```

```{r}
scored_forecast <- combined %>% filter(!is.na(obs)) %>% 
  mutate(crps = scoringRules::crps_norm(y = obs, mean = mean, sd = sd),
         logs = scoringRules::logs_norm(y = obs, mean = mean, sd = sd))

```

```{r}
interval <- scored_forecast %>% group_by(theme, team, issue_date, target, siteID) %>% 
  mutate(interval = time - lag(time)) %>% ungroup() %>%
  count(interval, sort=TRUE) %>% pull(interval) %>% first()


df <- scored_forecast %>% 
  group_by(theme, team, issue_date, target, siteID) %>% 
  summarise(forecast_start_time = min(time)-interval, .groups = "drop") %>% 
  right_join(scored_forecast) %>% 
  mutate(horizon = time - forecast_start_time)


df %>% count(horizon, sort=TRUE)
```





````{r}
df %>%
  filter(
    #horizon >= 28,
    target == "abundance"
    ) %>% 
  group_by(theme, team, time, siteID) %>%
  slice_max(issue_date) %>%
  slice_min(horizon) %>% 
  na.omit() %>% 
  filter(siteID %in% top_sites) %>%
  ggplot(aes(x=time)) +
  geom_point(aes(y = obs), size = .05) + 
   geom_ribbon(aes(ymin = mean-2*sd, ymax = mean+2*sd, fill=team, col=team),
                   alpha = 0.2, show.legend=FALSE) +
  geom_line(aes(y = mean, col=team)) +
  facet_wrap(~siteID, scales = "free") + 
  ggtitle("30th day ahead")
```


